/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NNetwork */

#ifndef _Included_NNetwork
#define _Included_NNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NNetwork
 * Method:    classifyPNN
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_NNetwork_classifyPNN
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     NNetwork
 * Method:    classifyBPN
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_NNetwork_classifyBPN
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     NNetwork
 * Method:    classifyUKN
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_NNetwork_classifyUKN
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
